export enum FraudAlertType {
  EXCESSIVE_HOURLY_ACTIVITY = 'EXCESSIVE_HOURLY_ACTIVITY',
  EXCESSIVE_DAILY_ACTIVITY = 'EXCESSIVE_DAILY_ACTIVITY',
  DUPLICATE_DOCUMENT_HASH = 'DUPLICATE_DOCUMENT_HASH',
  ABNORMAL_BURST = 'ABNORMAL_BURST',
}